CREATE TABLE service_order_data_import_audit_information (
    service_order_data_import_audit_information_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_number_of_records INT NOT NULL,
    generated_by VARCHAR(255) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    last_modified_by VARCHAR(255) NOT NULL,
    CONSTRAINT pk_service_order_data_import_audit_information PRIMARY KEY (service_order_data_import_audit_information_id)
);

CREATE TABLE service_order (
    service_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_number VARCHAR(255) NOT NULL,
    service_order_number VARCHAR(255) NOT NULL,
    closed_date VARCHAR(40),
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    last_modified_by VARCHAR(255) NOT NULL,
    service_order_data_import_audit_information_id BIGINT,
    CONSTRAINT pk_service_order PRIMARY KEY (service_order_id)
);

ALTER TABLE service_order ADD CONSTRAINT FK_SERVICE_ORDER_ON_SERVICE_ORDER_DATA_IMPORT_AUDIT_INFORMATION FOREIGN KEY (service_order_data_import_audit_information_id) REFERENCES service_order_data_import_audit_information (service_order_data_import_audit_information_id);

CREATE TABLE service_attempt (
    service_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    call_date VARCHAR(40),
    technician_employee_number VARCHAR(100),
    call_code VARCHAR(255),
    start_time VARCHAR(40),
    end_time VARCHAR(40),
    transit_time_in_minutes VARCHAR(40),
    technician_comment1 VARCHAR(255),
    technician_comment2 VARCHAR(255),
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    last_modified_by VARCHAR(255) NOT NULL,
    service_order_id BIGINT,
    CONSTRAINT pk_service_attempt PRIMARY KEY (service_attempt_id)
);

-- Add foreign key constraints
ALTER TABLE service_attempt ADD CONSTRAINT FK_SERVICE_ATTEMPT_ON_SERVICE_ORDER FOREIGN KEY (service_order_id) REFERENCES service_order (service_order_id);

-- Add indexes for foreign keys for query optimization
CREATE INDEX idx_service_order_service_order_data_import_audit_information_id ON service_order (service_order_data_import_audit_information_id);
CREATE INDEX idx_service_attempt_service_order_id ON service_attempt (service_order_id);