package com.shs.b2bm.claim.service.entities;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Contains audit information related to service order data processing or generation. Tracks
 * information about batch processing and system operations.
 */
@Entity
@Table(name = "service_order_data_import_audit_information")
@Getter
@Setter
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class ServiceOrderDataImportAuditInformation extends BaseEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long serviceOrderDataImportAuditInformationId;

  @Min(value = 0, message = "Total number of records cannot be negative")
  @Column(nullable = false)
  private int totalNumberOfRecords;

  @NotBlank(message = "Generated by information cannot be blank")
  @Column(nullable = false)
  private String generatedBy;

  @OneToMany(
      mappedBy = "serviceOrderDataImportAuditInformation",
      cascade = CascadeType.ALL,
      fetch = FetchType.LAZY)
  @ToString.Exclude
  private List<ServiceOrder> serviceOrders = new ArrayList<>();
}
